apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex-sa
  namespace: soc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-config
  namespace: soc
data:
  application.conf: |
   play {
      http {
        port = 9001
        secret.key = ${?CORTEX_HTTP_SECRET}
      }
      http.parser.maxDiskBuffer = 100MB
      http.parser.maxMemoryBuffer = 100MB
    }

    cortex {
      analyzer {
          # Directory that holds analyzers
        urls = [
          "https://catalogs.download.strangebee.com/latest/json/analyzers.json",
          "/opt/cortex/analyzers" 
        ]

        fork-join-executor {
          # Min number of threads available for analyze
          parallelism-min = 2
          # Parallelism (threads) ... ceil(available processors * factor)
          parallelism-factor = 2.0
          # Max number of threads available for analyze
          parallelism-max = 4
        }
      }

      responder {
        # Directory that holds responders
        urls = [
          "https://catalogs.download.strangebee.com/latest/json/responders.json",
          "/opt/cortex/responders"
        ]

        fork-join-executor {
          # Min number of threads available for analyze
          parallelism-min = 2
          # Parallelism (threads) ... ceil(available processors * factor)
          parallelism-factor = 2.0
          # Max number of threads available for analyze
          parallelism-max = 4
        }
      }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-virustotal-config
  namespace: soc
data:
  virustotal.json: |
    {
      "key": "${VIRUSTOTAL_API_KEY}"
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-data-pvc
  namespace: soc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-analyzers-pvc
  namespace: soc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-shared-fs-claim
  namespace: soc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-responders-pvc
  namespace: soc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  namespace: soc
  labels:
    app: cortex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      serviceAccountName: cortex-sa
      initContainers:
        - name: check-elasticsearch
          image: curlimages/curl:8.17.0
          command: ["sh", "-c", "until curl -s http://elasticsearch.soc.svc.cluster.local:9200; do echo waiting for ES; sleep 5; done"]
        - name: install-cortexutils
          image: python:3.11
          command: 
            - sh
            - -c
            - |
              pip3 install --upgrade pip
              pip3 install cortexutils
              pip3 install -r /tmp/requirements.txt || true
          volumeMounts:
            - name: python-libs
              mountPath: /usr/local/lib/python3.11/site-packages
      containers:
        - name: cortex
          image: thehiveproject/cortex:4.0
          ports:
            - containerPort: 9001
              name: http
          env:
            - name: CORTEX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cortex-api-secret
                  key: CORTEX_API_KEY
            - name: CORTEX_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: cortex-http-secret
                  key: CORTEX_HTTP_SECRET
            - name: PYTHONPATH
              value: "/usr/local/lib/python3.11/site-packages"
            - name: VIRUSTOTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: virustotal-secret
                  key: VIRUSTOTAL_API_KEY

          volumeMounts:
            - name: cortex-data-pvc
              mountPath: /opt/cortex/data
            - name: cortex-analyzers-pvc
              mountPath: /opt/cortex/analyzers
            - name: cortex-shared-fs-claim
              mountPath: /opt/cortex/shared
            # Mount ConfigMap directly as application.conf
            - name: cortex-config
              mountPath: /opt/cortex/conf/application.conf
              subPath: application.conf
            - name: python-libs
              mountPath: /usr/local/lib/python3.11/site-packages
            - name: cortex-virustotal-config
              mountPath: /opt/cortex/analyzers/virustotal
              readOnly: true
            - name: cortex-responders-pvc
              mountPath: /opt/cortex/responders

          startupProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /
              port: 9001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
        # - name: python3-sidecar
        #   image: python:3.11
        #   command: ["sleep", "infinity"]
        #   volumeMounts:
        #     - name: cortex-analyzers-pvc
        #       mountPath: /opt/cortex/analyzers
        #        Sidecar to pull analyzers and responders
        - name: cortex-sidecar
          image: python:3.11-slim
          command: ["/bin/sh","-c"]
          args:
            - |
              set -ex

              # Clone or update analyzers
              if [ -d /opt/cortex/analyzers/.git ]; then
                cd /opt/cortex/analyzers && git pull
              else
                git clone https://github.com/TheHive-Project/Cortex-Analyzers.git /opt/cortex/analyzers
              fi

              # Clone or update responders
              if [ -d /opt/cortex/responders/.git ]; then
                cd /opt/cortex/responders && git pull
              else
                git clone https://github.com/TheHive-Project/Cortex-Responders.git /opt/cortex/responders
              fi

              # # Install Python dependencies for analyzers/responders
              # for I in $(find /opt/cortex/analyzers -name 'requirements.txt'); do pip3 install -r $I || true; done
              # for I in $(find /opt/cortex/responders -name 'requirements.txt'); do pip3 install -r $I || true; done

              # # Fix ownership so Cortex (UID 1000) can access
              # chown -R 1000:1000 /opt/cortex/analyzers /opt/cortex/responders

              # # Keep container alive if you want it running
              # tail -f /dev/null
          volumeMounts:
            - name: cortex-analyzers-pvc
              mountPath: /opt/cortex/analyzers
            - name: cortex-responders-pvc
              mountPath: /opt/cortex/responders

    
      volumes:
        - name: cortex-data-pvc
          persistentVolumeClaim:
            claimName: cortex-data-pvc
        - name: cortex-analyzers-pvc
          persistentVolumeClaim:
            claimName: cortex-analyzers-pvc
        - name: cortex-shared-fs-claim
          persistentVolumeClaim:
            claimName: cortex-shared-fs-claim
        - name: cortex-config
          configMap:
            name: cortex-config
        - name: python-libs
          emptyDir: {}
        - name: cortex-virustotal-config
          configMap:
            name: cortex-virustotal-config
        - name: cortex-responders-pvc
          persistentVolumeClaim:
            claimName: cortex-responders-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cortex
  namespace: soc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.200.40
  selector:
    app: cortex
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001