apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehive-data-pvc
  namespace: soc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehive-index-pvc
  namespace: soc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
