apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehive-data-pvc
  namespace: soc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi

