http:
  routers:
    dashboard-router:
      rule: "Host(`trfk.leone.home`)"
      service: api@internal
      entryPoints: [websecure]
      tls: true
#      middlewares:
#       - authentik

    authentikop-router:
      rule: "Host(`authentik.leone.home`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      service: authentik-service
      entryPoints: [websecure]
      tls: true

    authentik-router:
      rule: "Host(`authentik.leone.home`)"
      service: authentik-service
      entryPoints: [websecure]
      tls: true

    vault-router:
      rule: "Host(`vault.leone.home`)"
      service: vault-service
      entryPoints: [websecure]
      tls: true

    portainer-router:
      rule: "Host(`portainer.leone.home`)"
      service: portainer-service
      entryPoints: [websecure]
      tls: true

    plex-router:
      rule: "Host(`plex.leone.home`)"
      service: plex-service
      entryPoints: [websecure]
      tls: true

    jellyfin-router:
      rule: "Host(`jellyfin.leone.home`)"
      service: jellyfin-service
      entryPoints: [websecure]
      tls: true

    tautulli-router:
      rule: "Host(`tautulli.leone.home`)"
      service: tautulli-service
      entryPoints: [websecure]
      tls: true

    pihole-router:
      rule: "Host(`pihole.leone.home`)"
      service: pihole-service
      entryPoints: [websecure]
      tls: true
      middlewares:
        - pihole-rewrite

    piholebk-router:
      rule: "Host(`piholebk.leone.home`)"
      service: piholebk-service
      entryPoints: [websecure]
      tls: true
      middlewares:
        - pihole-rewrite

    # uptimek-router:
    #   rule: "Host(`uptimek.leone.home`)"
    #   service: uptimek-service
    #   entryPoints: [websecure]
    #   tls: true

    #wazuh-router:
    #  rule: "Host(`wazuh.leone.home`)"
    #  service: wazuh-service
    #  entryPoints: [websecure]
    #  tls: treu

    splunk-router:
      rule: "Host(`splunk.leone.home`)"
      service: splunk-service
      entryPoints: [websecure]
      tls: true

    grafana-router:
      rule: "Host(`grafana.leone.home`)"
      service: grafana-service
      entryPoints: [websecure]
      tls: true

    checkmate-router:
      rule: "Host(`checkmate.leone.home`)"
      service: checkmate-service
      entryPoints: [websecure]
      tls: true

   chk-svr-router:
      rule: "Host(`chk-svr.leone.home`)"
      service: chk-svr-service
      entryPoints: [web]
      tls: false

    vas-router:
      rule: "Host(`vas.leone.home`)"
      service: vas-service
      entryPoints: [websecure]
      tls: true

  services:
    vault-service:
      loadBalancer:
        serversTransport: vault-tls
        servers:
          - url: "https://192.168.1.4:443"

    portainer-service:
      loadBalancer:
        serversTransport: portainer-tls
        servers:
          - url: "https://192.168.1.126:9443"
        passHostHeader: true
        healthCheck:
          path: "/"
          interval: "30s"

    plex-service:
      loadBalancer:
        serversTransport: plex-tls
        servers:
          - url: "https://192.168.1.136:32400"

    jellyfin-service:
      loadBalancer:
        servers:
          - url: "https://192.168.1.140:8096"

    tautulli-service:
      loadBalancer:
        servers:
          - url: "https://192.168.1.140:8181"

    pihole-service:
      loadBalancer:
        serversTransport: pihole-tls
        servers:
          - url: "http://192.168.1.250"

    piholebk-service:
      loadBalancer:
        serversTransport: piholebk-tls
        servers:
          - url: "http://192.168.1.126/admin/login"

    # uptimek-service:
    #   loadBalancer:
    #     serversTransport: uptimek-tls
    #     servers:
    #       - url: "http://192.168.1.181:3001"

     #wazuh-service:
     #  loadBalancer:
     #    serversTransport: wazuh-tls
     #    servers:
     #      - url: "https://wazuh.leone.home/app/login?nextUrl=%2F"
    #     passHostHeader: true

    splunk-service:
      loadBalancer:
        serversTransport: splunk-tls
        servers:
          - url: "http://192.168.1.109:8000"

    authentik-service:
      loadBalancer:
        serversTransport: authentik-tls
        servers:
          - url: "https://192.168.1.166:9443"

    grafana-service:
      loadBalancer:
        serversTransport: grafana-tls
        servers:
          - url: "http://192.168.1.246:3000"

    checkmate-service:
      loadBalancer:
        serversTransport: checkmate-tls
        servers:
          - url: "http://192.168.1.126:7000"

    chk-svr-service:
      loadBalancer:
      #  serversTransport: checkmate-tls
        servers:
          - url: "http://192.168.1.126:52345"

    vas-service:
      loadBalancer:
        serversTransport: vas-tls
        servers:
          - url: "http://192.168.1.166:9392"

  middlewares:
    dashboard-auth:
       basicAuth:
         users:
           - "admin:$$apr1$$r4U7vCvc$$dbZMEYMYtLPNPVaNYVZ1S0"

    pihole-strip:
      stripPrefix:
        prefixes:
          - /admin
    pihole-rewrite:
      replacePathRegex:
        regex: "^/$"
        replacement: "/admin"

    authentik:
       forwardAuth:
         address: "http:///authentik_proxy:9000/outpost.goauthentik.io/auth/traefik"
         trustForwardHeader: true
         authResponseHeadersRegex: "^X-authentik-"
         authResponseHeaders:
           - X-authentik-username
           - X-authentik-groups
           - X-authentik-entitlements
           - X-authentik-email
           - X-authentik-name
           - X-authentik-uid
           - X-authentik-jwt
           - X-authentik-meta-jwks
           - X-authentik-meta-outpost
           - X-authentik-meta-provider
           - X-authentik-meta-app
           - X-authentik-meta-version

    pihole-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Port: "443"

  serversTransports:

    vault-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: vault.leone.home

    portainer-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: portainer.leone.home

    piholebk-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: piholebk.leone.home
      insecureSkipVerify: true

    pihole-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: pihole.leone.home
      insecureSkipVerify: true

    plex-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: plex.leone.home
      insecureSkipVerify: true

    # uptimek-tls:
    #   rootCAs:
    #     - /certs/root_ca.crt
    #   serverName: uptimek.leone.home
    #   insecureSkipVerify: true

    authentik-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: authentik.leone.home

     #wazuh-tls:
     #  rootCAs:
     #    - /certs/root_ca.crt
     #  serverName: wazuh.leone.home
     #  insecureSkipVerify: true

    splunk-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: splunk.leone.home
      insecureSkipVerify: true

    grafana-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: grafana.leone.home
      insecureSkipVerify: true

    checkmate-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: checkmate.leone.home
      insecureSkipVerify: true

    vas-tls:
      rootCAs:
        - /certs/root_ca.crt
      serverName: vas.leone.home
      insecureSkipVerify: false

tls:
  certificates:
    - certFile: /certs/chained_whoami.crt
      keyFile:  /certs/whoami.key
    - certFile: /certs/fullchain_trfk.crt
      keyFile:  /certs/trfk.key
    - certFile: /certs/fullchain_portainer.crt
      keyFile: /certs/portainer.key
    - certFile: /certs/fullchain_vault.crt
      keyFile: /certs/vault.key
    - certFile: /certs/fullchain_pihole.crt
      keyFile: /certs/pihole.key
    - certFile: /certs/fullchain_piholebk.crt
      keyFile: /certs/piholebk.key
    - certFile: /certs/fullchain_plex.crt
      keyFile: /certs/plex.key
    - certFile: /certs/fullchain_uptimek.crt
      keyFile: /certs/uptimek.key
    - certFile: /certs/fullchain_authentik.crt
      keyFile: /certs/authentik.key
    #- certFile: /certs/fullchain_wazuh.crt
    #  keyFile: /certs/wazuh.key
    - certFile: /certs/fullchain_splunk.crt
      keyFile: /certs/splunk.key
    - certFile: /certs/fullchain_grafana.crt
      keyFile: /certs/grafana.key
    - certFile: /certs/fullchain_checkmate.crt
      keyFile: /certs/checkmate.key
    - certFile: /certs/fullchain_vas.crt
      keyFile: /certs/vas.key

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0