groups:
- name: blackbox_alerts
  rules:

  # 🔍 HTTP/HTTPS Probes
  - alert: EndpointDown_HTTP
    expr: probe_success{job="blackbox_http"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "HTTP endpoint {{ $labels.instance }} is down"
      description: "Blackbox probe failed for {{ $labels.instance }}. Status code: {{ $value }}"

  # 🧊 TLS Expiry Check
  - alert: TLSCertificateExpiringSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "TLS cert for {{ $labels.instance }} expires soon"
      description: "Certificate expires in less than 7 days. Renew before downtime."

  # 🧪 Discord Webhook Monitoring
  - alert: DiscordWebhookUnreachable
    expr: probe_success{job="discord_webhook"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Discord webhook {{ $labels.instance }} is unreachable"
      description: "Webhook failed to respond. Check Discord API or network connectivity."

  # 📡 ICMP Ping
  - alert: HostUnreachable_ICMP
    expr: probe_success{job="icmp_ping"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Host {{ $labels.instance }} is unreachable via ICMP"
      description: "Ping failed. Host may be offline or blocked by firewall."

  # 🔌 TCP Port Check (SSH)
  - alert: TCPPortDown_SSH
    expr: probe_success{job="tcp_ssh"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "SSH port unreachable on {{ $labels.instance }}"
      description: "TCP probe to port 22 failed. Check firewall or service status."

  # 🔐 TCP Port Check (HTTPS)
  - alert: TCPPortDown_HTTPS
    expr: probe_success{job="tcp_https"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "HTTPS port unreachable on {{ $labels.instance }}"
      description: "TCP probe to port 443 failed. Check firewall or service status."