- hosts: all
  become: true
  tasks:
    - name: Update all packages on RedHat family
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Update all packages on Debian family
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    # Debian reboot check
    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"

    # RedHat reboot check
    - name: Check if reboot is required (RedHat family)
      command: needs-restarting -r
      register: needs_reboot
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Reboot if required (Debian)
      reboot:
      when: reboot_required.stat.exists

    - name: Reboot if required (RedHat)
      reboot:
      when: needs_reboot.rc == 1