version: "3.9"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"

    dns:
      - 192.168.1.250
      - 192.168.1.126

    environment:
      TZ: "America/New_York"
      WEBPASSWORD: "paul"
      DNSMASQ_USER: "pihole"

    volumes:
      - /opt/pihole/etc-pihole:/etc/pihole
      - /opt/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost/admin/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
      